#!/usr/bin/perl

# Configure acsint.c to your keyboard layout.
# This is necessary for echo mode.
# Don't just run this automatically; run keycodes first, and see if the
# resulting strings seem sane to you. If they do, then run keyconfigure,
# and then make modules.

use Encode;

# In case . isn't in your PATH, and this only makes sense
# in the drivers directory anyways.
if(!open KC, "./keycodes|") {
print "could not execute keycodes\n";
exit 1;
}
my @newarrays = <KC>;
close KC;
if($#newarrays != 7) {
print "Output from keycodes is not 8 lines as expected";
exit 1;
}

open layout, ">../jupiter/keylayout.c";
# I assume the lower case is all ascii
print layout $newarrays[0];
print layout $newarrays[1];
# I assume upper case is convertable to iso8859-1
# $o is the octants
print layout $newarrays[2];
my $o;
$o = decode "utf8", $newarrays[3];
$o = encode "iso-8859-1", $o;
print layout $o;
close layout;

open inf, "acsint.in";
open outf, ">acsint.c";
my $through = 1;
while(<inf>) {
if(/static const char lowercode/) {
$through = 0;
print outf @newarrays;
}
$through = 1 if /#define KEYCODELIMIT/;
print outf if $through;
}
close inf;
close outf;
